#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSDataClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tender")]
	public partial class SecurityDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaplicacione(aplicacione instance);
    partial void Updateaplicacione(aplicacione instance);
    partial void Deleteaplicacione(aplicacione instance);
    partial void Insertprofile(profile instance);
    partial void Updateprofile(profile instance);
    partial void Deleteprofile(profile instance);
    partial void Insertusuarios_aplicacione(usuarios_aplicacione instance);
    partial void Updateusuarios_aplicacione(usuarios_aplicacione instance);
    partial void Deleteusuarios_aplicacione(usuarios_aplicacione instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public SecurityDBDataContext() : 
				base(global::TCSDataClasses.Properties.Settings.Default.TenderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<aplicacione> aplicaciones
		{
			get
			{
				return this.GetTable<aplicacione>();
			}
		}
		
		public System.Data.Linq.Table<profile> profiles
		{
			get
			{
				return this.GetTable<profile>();
			}
		}
		
		public System.Data.Linq.Table<usuarios_aplicacione> usuarios_aplicaciones
		{
			get
			{
				return this.GetTable<usuarios_aplicacione>();
			}
		}
		
		public System.Data.Linq.Table<usuarios_perfile> usuarios_perfiles
		{
			get
			{
				return this.GetTable<usuarios_perfile>();
			}
		}
		
		public System.Data.Linq.Table<profile_menu_option> profile_menu_options
		{
			get
			{
				return this.GetTable<profile_menu_option>();
			}
		}
		
		public System.Data.Linq.Table<almacena_password> almacena_passwords
		{
			get
			{
				return this.GetTable<almacena_password>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<Control_Tiempo_Acceso_web> Control_Tiempo_Acceso_web
		{
			get
			{
				return this.GetTable<Control_Tiempo_Acceso_web>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insert_historial_password")]
		public int sp_insert_historial_password([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(15)")] string cod_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(3)")] string cod_aplicacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(20)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod_usuario, cod_aplicacion, pass);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aplicaciones")]
	public partial class aplicacione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo_aplicacion;
		
		private string _nombre_aplicacion;
		
		private char _activa;
		
		private string _version;
		
		private EntitySet<profile> _profiles;
		
		private EntitySet<usuarios_aplicacione> _usuarios_aplicaciones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_aplicacionChanging(string value);
    partial void Oncodigo_aplicacionChanged();
    partial void Onnombre_aplicacionChanging(string value);
    partial void Onnombre_aplicacionChanged();
    partial void OnactivaChanging(char value);
    partial void OnactivaChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    #endregion
		
		public aplicacione()
		{
			this._profiles = new EntitySet<profile>(new Action<profile>(this.attach_profiles), new Action<profile>(this.detach_profiles));
			this._usuarios_aplicaciones = new EntitySet<usuarios_aplicacione>(new Action<usuarios_aplicacione>(this.attach_usuarios_aplicaciones), new Action<usuarios_aplicacione>(this.detach_usuarios_aplicaciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_aplicacion", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_aplicacion
		{
			get
			{
				return this._codigo_aplicacion;
			}
			set
			{
				if ((this._codigo_aplicacion != value))
				{
					this.Oncodigo_aplicacionChanging(value);
					this.SendPropertyChanging();
					this._codigo_aplicacion = value;
					this.SendPropertyChanged("codigo_aplicacion");
					this.Oncodigo_aplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_aplicacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombre_aplicacion
		{
			get
			{
				return this._nombre_aplicacion;
			}
			set
			{
				if ((this._nombre_aplicacion != value))
				{
					this.Onnombre_aplicacionChanging(value);
					this.SendPropertyChanging();
					this._nombre_aplicacion = value;
					this.SendPropertyChanged("nombre_aplicacion");
					this.Onnombre_aplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activa", DbType="Char(1) NOT NULL")]
		public char activa
		{
			get
			{
				return this._activa;
			}
			set
			{
				if ((this._activa != value))
				{
					this.OnactivaChanging(value);
					this.SendPropertyChanging();
					this._activa = value;
					this.SendPropertyChanged("activa");
					this.OnactivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aplicacione_profile", Storage="_profiles", ThisKey="codigo_aplicacion", OtherKey="application_id")]
		public EntitySet<profile> profiles
		{
			get
			{
				return this._profiles;
			}
			set
			{
				this._profiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aplicacione_usuarios_aplicacione", Storage="_usuarios_aplicaciones", ThisKey="codigo_aplicacion", OtherKey="codigo_aplicacion")]
		public EntitySet<usuarios_aplicacione> usuarios_aplicaciones
		{
			get
			{
				return this._usuarios_aplicaciones;
			}
			set
			{
				this._usuarios_aplicaciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_profiles(profile entity)
		{
			this.SendPropertyChanging();
			entity.aplicacione = this;
		}
		
		private void detach_profiles(profile entity)
		{
			this.SendPropertyChanging();
			entity.aplicacione = null;
		}
		
		private void attach_usuarios_aplicaciones(usuarios_aplicacione entity)
		{
			this.SendPropertyChanging();
			entity.aplicacione = this;
		}
		
		private void detach_usuarios_aplicaciones(usuarios_aplicacione entity)
		{
			this.SendPropertyChanging();
			entity.aplicacione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profile")]
	public partial class profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _application_id;
		
		private string _profile_id;
		
		private string _profile_desc;
		
		private string _service_scope;
		
		private string _location_scope;
		
		private string _usuario_creacion;
		
		private System.DateTime _fecha_hora_creacion;
		
		private string _usuario_ult_act;
		
		private System.DateTime _fecha_hora_ult_act;
		
		private EntityRef<aplicacione> _aplicacione;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onapplication_idChanging(string value);
    partial void Onapplication_idChanged();
    partial void Onprofile_idChanging(string value);
    partial void Onprofile_idChanged();
    partial void Onprofile_descChanging(string value);
    partial void Onprofile_descChanged();
    partial void Onservice_scopeChanging(string value);
    partial void Onservice_scopeChanged();
    partial void Onlocation_scopeChanging(string value);
    partial void Onlocation_scopeChanged();
    partial void Onusuario_creacionChanging(string value);
    partial void Onusuario_creacionChanged();
    partial void Onfecha_hora_creacionChanging(System.DateTime value);
    partial void Onfecha_hora_creacionChanged();
    partial void Onusuario_ult_actChanging(string value);
    partial void Onusuario_ult_actChanged();
    partial void Onfecha_hora_ult_actChanging(System.DateTime value);
    partial void Onfecha_hora_ult_actChanged();
    #endregion
		
		public profile()
		{
			this._aplicacione = default(EntityRef<aplicacione>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_id", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string application_id
		{
			get
			{
				return this._application_id;
			}
			set
			{
				if ((this._application_id != value))
				{
					if (this._aplicacione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onapplication_idChanging(value);
					this.SendPropertyChanging();
					this._application_id = value;
					this.SendPropertyChanged("application_id");
					this.Onapplication_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_id", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string profile_id
		{
			get
			{
				return this._profile_id;
			}
			set
			{
				if ((this._profile_id != value))
				{
					this.Onprofile_idChanging(value);
					this.SendPropertyChanging();
					this._profile_id = value;
					this.SendPropertyChanged("profile_id");
					this.Onprofile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_desc", DbType="Char(40) NOT NULL", CanBeNull=false)]
		public string profile_desc
		{
			get
			{
				return this._profile_desc;
			}
			set
			{
				if ((this._profile_desc != value))
				{
					this.Onprofile_descChanging(value);
					this.SendPropertyChanging();
					this._profile_desc = value;
					this.SendPropertyChanged("profile_desc");
					this.Onprofile_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_scope", DbType="Char(2)")]
		public string service_scope
		{
			get
			{
				return this._service_scope;
			}
			set
			{
				if ((this._service_scope != value))
				{
					this.Onservice_scopeChanging(value);
					this.SendPropertyChanging();
					this._service_scope = value;
					this.SendPropertyChanged("service_scope");
					this.Onservice_scopeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location_scope", DbType="Char(2)")]
		public string location_scope
		{
			get
			{
				return this._location_scope;
			}
			set
			{
				if ((this._location_scope != value))
				{
					this.Onlocation_scopeChanging(value);
					this.SendPropertyChanging();
					this._location_scope = value;
					this.SendPropertyChanged("location_scope");
					this.Onlocation_scopeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_creacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_creacion
		{
			get
			{
				return this._usuario_creacion;
			}
			set
			{
				if ((this._usuario_creacion != value))
				{
					this.Onusuario_creacionChanging(value);
					this.SendPropertyChanging();
					this._usuario_creacion = value;
					this.SendPropertyChanged("usuario_creacion");
					this.Onusuario_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_creacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_creacion
		{
			get
			{
				return this._fecha_hora_creacion;
			}
			set
			{
				if ((this._fecha_hora_creacion != value))
				{
					this.Onfecha_hora_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_hora_creacion = value;
					this.SendPropertyChanged("fecha_hora_creacion");
					this.Onfecha_hora_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_ult_act", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_ult_act
		{
			get
			{
				return this._usuario_ult_act;
			}
			set
			{
				if ((this._usuario_ult_act != value))
				{
					this.Onusuario_ult_actChanging(value);
					this.SendPropertyChanging();
					this._usuario_ult_act = value;
					this.SendPropertyChanged("usuario_ult_act");
					this.Onusuario_ult_actChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_ult_act", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_ult_act
		{
			get
			{
				return this._fecha_hora_ult_act;
			}
			set
			{
				if ((this._fecha_hora_ult_act != value))
				{
					this.Onfecha_hora_ult_actChanging(value);
					this.SendPropertyChanging();
					this._fecha_hora_ult_act = value;
					this.SendPropertyChanged("fecha_hora_ult_act");
					this.Onfecha_hora_ult_actChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aplicacione_profile", Storage="_aplicacione", ThisKey="application_id", OtherKey="codigo_aplicacion", IsForeignKey=true)]
		public aplicacione aplicacione
		{
			get
			{
				return this._aplicacione.Entity;
			}
			set
			{
				aplicacione previousValue = this._aplicacione.Entity;
				if (((previousValue != value) 
							|| (this._aplicacione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aplicacione.Entity = null;
						previousValue.profiles.Remove(this);
					}
					this._aplicacione.Entity = value;
					if ((value != null))
					{
						value.profiles.Add(this);
						this._application_id = value.codigo_aplicacion;
					}
					else
					{
						this._application_id = default(string);
					}
					this.SendPropertyChanged("aplicacione");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios_aplicaciones")]
	public partial class usuarios_aplicacione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo_usuario;
		
		private string _codigo_aplicacion;
		
		private System.Nullable<System.DateTime> _fecha_inicio;
		
		private System.Nullable<System.DateTime> _fecha_fin;
		
		private System.Nullable<char> _tipo_usuario;
		
		private System.Nullable<System.DateTime> _fecha_ultimo_acceso;
		
		private System.Nullable<int> _intentos_hechos;
		
		private System.Nullable<System.DateTime> _Fecha_Intento_Fallido;
		
		private System.Nullable<char> _Bloqueado;
		
		private EntityRef<aplicacione> _aplicacione;
		
		private EntityRef<usuario> _usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_usuarioChanging(string value);
    partial void Oncodigo_usuarioChanged();
    partial void Oncodigo_aplicacionChanging(string value);
    partial void Oncodigo_aplicacionChanged();
    partial void Onfecha_inicioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_finChanged();
    partial void Ontipo_usuarioChanging(System.Nullable<char> value);
    partial void Ontipo_usuarioChanged();
    partial void Onfecha_ultimo_accesoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ultimo_accesoChanged();
    partial void Onintentos_hechosChanging(System.Nullable<int> value);
    partial void Onintentos_hechosChanged();
    partial void OnFecha_Intento_FallidoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_Intento_FallidoChanged();
    partial void OnBloqueadoChanging(System.Nullable<char> value);
    partial void OnBloqueadoChanged();
    #endregion
		
		public usuarios_aplicacione()
		{
			this._aplicacione = default(EntityRef<aplicacione>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_usuario", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_usuario
		{
			get
			{
				return this._codigo_usuario;
			}
			set
			{
				if ((this._codigo_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._codigo_usuario = value;
					this.SendPropertyChanged("codigo_usuario");
					this.Oncodigo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_aplicacion", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_aplicacion
		{
			get
			{
				return this._codigo_aplicacion;
			}
			set
			{
				if ((this._codigo_aplicacion != value))
				{
					if (this._aplicacione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_aplicacionChanging(value);
					this.SendPropertyChanging();
					this._codigo_aplicacion = value;
					this.SendPropertyChanged("codigo_aplicacion");
					this.Oncodigo_aplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="Char(1)")]
		public System.Nullable<char> tipo_usuario
		{
			get
			{
				return this._tipo_usuario;
			}
			set
			{
				if ((this._tipo_usuario != value))
				{
					this.Ontipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario = value;
					this.SendPropertyChanged("tipo_usuario");
					this.Ontipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ultimo_acceso", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_ultimo_acceso
		{
			get
			{
				return this._fecha_ultimo_acceso;
			}
			set
			{
				if ((this._fecha_ultimo_acceso != value))
				{
					this.Onfecha_ultimo_accesoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ultimo_acceso = value;
					this.SendPropertyChanged("fecha_ultimo_acceso");
					this.Onfecha_ultimo_accesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intentos_hechos", DbType="Int")]
		public System.Nullable<int> intentos_hechos
		{
			get
			{
				return this._intentos_hechos;
			}
			set
			{
				if ((this._intentos_hechos != value))
				{
					this.Onintentos_hechosChanging(value);
					this.SendPropertyChanging();
					this._intentos_hechos = value;
					this.SendPropertyChanged("intentos_hechos");
					this.Onintentos_hechosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Intento_Fallido", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Intento_Fallido
		{
			get
			{
				return this._Fecha_Intento_Fallido;
			}
			set
			{
				if ((this._Fecha_Intento_Fallido != value))
				{
					this.OnFecha_Intento_FallidoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Intento_Fallido = value;
					this.SendPropertyChanged("Fecha_Intento_Fallido");
					this.OnFecha_Intento_FallidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloqueado", DbType="Char(1)")]
		public System.Nullable<char> Bloqueado
		{
			get
			{
				return this._Bloqueado;
			}
			set
			{
				if ((this._Bloqueado != value))
				{
					this.OnBloqueadoChanging(value);
					this.SendPropertyChanging();
					this._Bloqueado = value;
					this.SendPropertyChanged("Bloqueado");
					this.OnBloqueadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aplicacione_usuarios_aplicacione", Storage="_aplicacione", ThisKey="codigo_aplicacion", OtherKey="codigo_aplicacion", IsForeignKey=true)]
		public aplicacione aplicacione
		{
			get
			{
				return this._aplicacione.Entity;
			}
			set
			{
				aplicacione previousValue = this._aplicacione.Entity;
				if (((previousValue != value) 
							|| (this._aplicacione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aplicacione.Entity = null;
						previousValue.usuarios_aplicaciones.Remove(this);
					}
					this._aplicacione.Entity = value;
					if ((value != null))
					{
						value.usuarios_aplicaciones.Add(this);
						this._codigo_aplicacion = value.codigo_aplicacion;
					}
					else
					{
						this._codigo_aplicacion = default(string);
					}
					this.SendPropertyChanged("aplicacione");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_usuarios_aplicacione", Storage="_usuario", ThisKey="codigo_usuario", OtherKey="codigo_usuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.usuarios_aplicaciones.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.usuarios_aplicaciones.Add(this);
						this._codigo_usuario = value.codigo_usuario;
					}
					else
					{
						this._codigo_usuario = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios_perfiles")]
	public partial class usuarios_perfile
	{
		
		private string _codigo_usuario;
		
		private string _codigo_aplicacion;
		
		private string _codigo_perfil;
		
		private System.Nullable<char> _tipo_usuario;
		
		private System.Nullable<System.DateTime> _fecha_inicio;
		
		private System.Nullable<System.DateTime> _fecha_fin;
		
		private string _usuario_creacion;
		
		private System.DateTime _fecha_hora_creacion;
		
		private string _usuario_ult_act;
		
		private System.DateTime _fecha_hora_ult_act;
		
		private string _perfil_servicios;
		
		private string _perfil_localidades;
		
		private string _codigo_naviera_csav;
		
		public usuarios_perfile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_usuario", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string codigo_usuario
		{
			get
			{
				return this._codigo_usuario;
			}
			set
			{
				if ((this._codigo_usuario != value))
				{
					this._codigo_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_aplicacion", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string codigo_aplicacion
		{
			get
			{
				return this._codigo_aplicacion;
			}
			set
			{
				if ((this._codigo_aplicacion != value))
				{
					this._codigo_aplicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_perfil", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string codigo_perfil
		{
			get
			{
				return this._codigo_perfil;
			}
			set
			{
				if ((this._codigo_perfil != value))
				{
					this._codigo_perfil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="Char(1)")]
		public System.Nullable<char> tipo_usuario
		{
			get
			{
				return this._tipo_usuario;
			}
			set
			{
				if ((this._tipo_usuario != value))
				{
					this._tipo_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this._fecha_inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this._fecha_fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_creacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_creacion
		{
			get
			{
				return this._usuario_creacion;
			}
			set
			{
				if ((this._usuario_creacion != value))
				{
					this._usuario_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_creacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_creacion
		{
			get
			{
				return this._fecha_hora_creacion;
			}
			set
			{
				if ((this._fecha_hora_creacion != value))
				{
					this._fecha_hora_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_ult_act", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_ult_act
		{
			get
			{
				return this._usuario_ult_act;
			}
			set
			{
				if ((this._usuario_ult_act != value))
				{
					this._usuario_ult_act = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_ult_act", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_ult_act
		{
			get
			{
				return this._fecha_hora_ult_act;
			}
			set
			{
				if ((this._fecha_hora_ult_act != value))
				{
					this._fecha_hora_ult_act = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_servicios", DbType="Char(2)")]
		public string perfil_servicios
		{
			get
			{
				return this._perfil_servicios;
			}
			set
			{
				if ((this._perfil_servicios != value))
				{
					this._perfil_servicios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perfil_localidades", DbType="Char(2)")]
		public string perfil_localidades
		{
			get
			{
				return this._perfil_localidades;
			}
			set
			{
				if ((this._perfil_localidades != value))
				{
					this._perfil_localidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_naviera_csav", DbType="Char(4)")]
		public string codigo_naviera_csav
		{
			get
			{
				return this._codigo_naviera_csav;
			}
			set
			{
				if ((this._codigo_naviera_csav != value))
				{
					this._codigo_naviera_csav = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profile_menu_option")]
	public partial class profile_menu_option
	{
		
		private string _application_id;
		
		private string _profile_id;
		
		private string _menu_option_id;
		
		private string _menu_option_access;
		
		private string _usuario_creacion;
		
		private System.DateTime _fecha_hora_creacion;
		
		private string _usuario_ult_act;
		
		private System.DateTime _fecha_hora_ult_act;
		
		private System.Nullable<char> _no_access_flag;
		
		private System.Nullable<char> _read_only_flag;
		
		private System.Nullable<char> _insert_flag;
		
		private System.Nullable<char> _edit_flag;
		
		private System.Nullable<char> _delete_flag;
		
		public profile_menu_option()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_id", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string application_id
		{
			get
			{
				return this._application_id;
			}
			set
			{
				if ((this._application_id != value))
				{
					this._application_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_id", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string profile_id
		{
			get
			{
				return this._profile_id;
			}
			set
			{
				if ((this._profile_id != value))
				{
					this._profile_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_option_id", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string menu_option_id
		{
			get
			{
				return this._menu_option_id;
			}
			set
			{
				if ((this._menu_option_id != value))
				{
					this._menu_option_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menu_option_access", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string menu_option_access
		{
			get
			{
				return this._menu_option_access;
			}
			set
			{
				if ((this._menu_option_access != value))
				{
					this._menu_option_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_creacion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_creacion
		{
			get
			{
				return this._usuario_creacion;
			}
			set
			{
				if ((this._usuario_creacion != value))
				{
					this._usuario_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_creacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_creacion
		{
			get
			{
				return this._fecha_hora_creacion;
			}
			set
			{
				if ((this._fecha_hora_creacion != value))
				{
					this._fecha_hora_creacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_ult_act", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string usuario_ult_act
		{
			get
			{
				return this._usuario_ult_act;
			}
			set
			{
				if ((this._usuario_ult_act != value))
				{
					this._usuario_ult_act = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora_ult_act", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora_ult_act
		{
			get
			{
				return this._fecha_hora_ult_act;
			}
			set
			{
				if ((this._fecha_hora_ult_act != value))
				{
					this._fecha_hora_ult_act = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_access_flag", DbType="Char(1)")]
		public System.Nullable<char> no_access_flag
		{
			get
			{
				return this._no_access_flag;
			}
			set
			{
				if ((this._no_access_flag != value))
				{
					this._no_access_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_read_only_flag", DbType="Char(1)")]
		public System.Nullable<char> read_only_flag
		{
			get
			{
				return this._read_only_flag;
			}
			set
			{
				if ((this._read_only_flag != value))
				{
					this._read_only_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_flag", DbType="Char(1)")]
		public System.Nullable<char> insert_flag
		{
			get
			{
				return this._insert_flag;
			}
			set
			{
				if ((this._insert_flag != value))
				{
					this._insert_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edit_flag", DbType="Char(1)")]
		public System.Nullable<char> edit_flag
		{
			get
			{
				return this._edit_flag;
			}
			set
			{
				if ((this._edit_flag != value))
				{
					this._edit_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_flag", DbType="Char(1)")]
		public System.Nullable<char> delete_flag
		{
			get
			{
				return this._delete_flag;
			}
			set
			{
				if ((this._delete_flag != value))
				{
					this._delete_flag = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.almacena_password")]
	public partial class almacena_password
	{
		
		private string _codigo_usuario;
		
		private string _codigo_aplicacion;
		
		private string _password;
		
		private System.Data.Linq.Binary _password_encriptada;
		
		private System.DateTime _fecha_cambio;
		
		public almacena_password()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_usuario", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string codigo_usuario
		{
			get
			{
				return this._codigo_usuario;
			}
			set
			{
				if ((this._codigo_usuario != value))
				{
					this._codigo_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_aplicacion", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string codigo_aplicacion
		{
			get
			{
				return this._codigo_aplicacion;
			}
			set
			{
				if ((this._codigo_aplicacion != value))
				{
					this._codigo_aplicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_encriptada", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary password_encriptada
		{
			get
			{
				return this._password_encriptada;
			}
			set
			{
				if ((this._password_encriptada != value))
				{
					this._password_encriptada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cambio", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				if ((this._fecha_cambio != value))
				{
					this._fecha_cambio = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codigo_usuario;
		
		private string _nombre;
		
		private System.DateTime _fecha_ult_password;
		
		private string _codigo_perfil;
		
		private string _password;
		
		private string _email;
		
		private EntitySet<usuarios_aplicacione> _usuarios_aplicaciones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_usuarioChanging(string value);
    partial void Oncodigo_usuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onfecha_ult_passwordChanging(System.DateTime value);
    partial void Onfecha_ult_passwordChanged();
    partial void Oncodigo_perfilChanging(string value);
    partial void Oncodigo_perfilChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public usuario()
		{
			this._usuarios_aplicaciones = new EntitySet<usuarios_aplicacione>(new Action<usuarios_aplicacione>(this.attach_usuarios_aplicaciones), new Action<usuarios_aplicacione>(this.detach_usuarios_aplicaciones));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_usuario", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codigo_usuario
		{
			get
			{
				return this._codigo_usuario;
			}
			set
			{
				if ((this._codigo_usuario != value))
				{
					this.Oncodigo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._codigo_usuario = value;
					this.SendPropertyChanged("codigo_usuario");
					this.Oncodigo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="Char(40) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ult_password", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_ult_password
		{
			get
			{
				return this._fecha_ult_password;
			}
			set
			{
				if ((this._fecha_ult_password != value))
				{
					this.Onfecha_ult_passwordChanging(value);
					this.SendPropertyChanging();
					this._fecha_ult_password = value;
					this.SendPropertyChanged("fecha_ult_password");
					this.Onfecha_ult_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_perfil", DbType="Char(3)")]
		public string codigo_perfil
		{
			get
			{
				return this._codigo_perfil;
			}
			set
			{
				if ((this._codigo_perfil != value))
				{
					this.Oncodigo_perfilChanging(value);
					this.SendPropertyChanging();
					this._codigo_perfil = value;
					this.SendPropertyChanged("codigo_perfil");
					this.Oncodigo_perfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_usuarios_aplicacione", Storage="_usuarios_aplicaciones", ThisKey="codigo_usuario", OtherKey="codigo_usuario")]
		public EntitySet<usuarios_aplicacione> usuarios_aplicaciones
		{
			get
			{
				return this._usuarios_aplicaciones;
			}
			set
			{
				this._usuarios_aplicaciones.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_usuarios_aplicaciones(usuarios_aplicacione entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_usuarios_aplicaciones(usuarios_aplicacione entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Control_Tiempo_Acceso_web")]
	public partial class Control_Tiempo_Acceso_web
	{
		
		private string _codigo_aplicacion;
		
		private System.Nullable<char> _activo;
		
		private System.Nullable<int> _dias_vigencia;
		
		private System.Nullable<int> _dias_aviso_previo;
		
		private System.Nullable<char> _usa_nueva_encriptacion;
		
		private int _intentos_permitidos;
		
		private int _password_almacenados;
		
		private int _segundos_inactividad;
		
		private System.Nullable<int> _largo_minimo;
		
		private System.Nullable<int> _minutos_bloqueo;
		
		public Control_Tiempo_Acceso_web()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_aplicacion", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string codigo_aplicacion
		{
			get
			{
				return this._codigo_aplicacion;
			}
			set
			{
				if ((this._codigo_aplicacion != value))
				{
					this._codigo_aplicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Char(1)")]
		public System.Nullable<char> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this._activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias_vigencia", DbType="Int")]
		public System.Nullable<int> dias_vigencia
		{
			get
			{
				return this._dias_vigencia;
			}
			set
			{
				if ((this._dias_vigencia != value))
				{
					this._dias_vigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias_aviso_previo", DbType="Int")]
		public System.Nullable<int> dias_aviso_previo
		{
			get
			{
				return this._dias_aviso_previo;
			}
			set
			{
				if ((this._dias_aviso_previo != value))
				{
					this._dias_aviso_previo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usa_nueva_encriptacion", DbType="Char(1)")]
		public System.Nullable<char> usa_nueva_encriptacion
		{
			get
			{
				return this._usa_nueva_encriptacion;
			}
			set
			{
				if ((this._usa_nueva_encriptacion != value))
				{
					this._usa_nueva_encriptacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intentos_permitidos", DbType="Int NOT NULL")]
		public int intentos_permitidos
		{
			get
			{
				return this._intentos_permitidos;
			}
			set
			{
				if ((this._intentos_permitidos != value))
				{
					this._intentos_permitidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_almacenados", DbType="Int NOT NULL")]
		public int password_almacenados
		{
			get
			{
				return this._password_almacenados;
			}
			set
			{
				if ((this._password_almacenados != value))
				{
					this._password_almacenados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundos_inactividad", DbType="Int NOT NULL")]
		public int segundos_inactividad
		{
			get
			{
				return this._segundos_inactividad;
			}
			set
			{
				if ((this._segundos_inactividad != value))
				{
					this._segundos_inactividad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_largo_minimo", DbType="Int")]
		public System.Nullable<int> largo_minimo
		{
			get
			{
				return this._largo_minimo;
			}
			set
			{
				if ((this._largo_minimo != value))
				{
					this._largo_minimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minutos_bloqueo", DbType="Int")]
		public System.Nullable<int> minutos_bloqueo
		{
			get
			{
				return this._minutos_bloqueo;
			}
			set
			{
				if ((this._minutos_bloqueo != value))
				{
					this._minutos_bloqueo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
