//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCSWebSite.TCSWcfServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_User", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TCSWebSite.TCSWcfServiceReference.dc_ApplicationUser applicationUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TCSWebSite.TCSWcfServiceReference.dc_Profile profileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TCSWebSite.TCSWcfServiceReference.dc_ApplicationUser applicationUser {
            get {
                return this.applicationUserField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationUserField, value) != true)) {
                    this.applicationUserField = value;
                    this.RaisePropertyChanged("applicationUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TCSWebSite.TCSWcfServiceReference.dc_Profile profile {
            get {
                return this.profileField;
            }
            set {
                if ((object.ReferenceEquals(this.profileField, value) != true)) {
                    this.profileField = value;
                    this.RaisePropertyChanged("profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_ApplicationUser", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_ApplicationUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> finishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> tryNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> finishDate {
            get {
                return this.finishDateField;
            }
            set {
                if ((this.finishDateField.Equals(value) != true)) {
                    this.finishDateField = value;
                    this.RaisePropertyChanged("finishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tryNumber {
            get {
                return this.tryNumberField;
            }
            set {
                if ((this.tryNumberField.Equals(value) != true)) {
                    this.tryNumberField = value;
                    this.RaisePropertyChanged("tryNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_Profile", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TCSWebSite.TCSWcfServiceReference.dc_Option[] optionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TCSWebSite.TCSWcfServiceReference.dc_Option[] options {
            get {
                return this.optionsField;
            }
            set {
                if ((object.ReferenceEquals(this.optionsField, value) != true)) {
                    this.optionsField = value;
                    this.RaisePropertyChanged("options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_Option", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_Option : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string menuOptionAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string menuOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TCSWebSite.TCSWcfServiceReference.dc_OptionApplication optionApplicationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string menuOptionAccess {
            get {
                return this.menuOptionAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.menuOptionAccessField, value) != true)) {
                    this.menuOptionAccessField = value;
                    this.RaisePropertyChanged("menuOptionAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string menuOptionId {
            get {
                return this.menuOptionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.menuOptionIdField, value) != true)) {
                    this.menuOptionIdField = value;
                    this.RaisePropertyChanged("menuOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TCSWebSite.TCSWcfServiceReference.dc_OptionApplication optionApplication {
            get {
                return this.optionApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.optionApplicationField, value) != true)) {
                    this.optionApplicationField = value;
                    this.RaisePropertyChanged("optionApplication");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_OptionApplication", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_OptionApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> levelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masterOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string menuOptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pageUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> levelId {
            get {
                return this.levelIdField;
            }
            set {
                if ((this.levelIdField.Equals(value) != true)) {
                    this.levelIdField = value;
                    this.RaisePropertyChanged("levelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masterOptionId {
            get {
                return this.masterOptionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.masterOptionIdField, value) != true)) {
                    this.masterOptionIdField = value;
                    this.RaisePropertyChanged("masterOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string menuOptionId {
            get {
                return this.menuOptionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.menuOptionIdField, value) != true)) {
                    this.menuOptionIdField = value;
                    this.RaisePropertyChanged("menuOptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pageUrl {
            get {
                return this.pageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.pageUrlField, value) != true)) {
                    this.pageUrlField = value;
                    this.RaisePropertyChanged("pageUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_TcsUser", Namespace="http://schemas.datacontract.org/2004/07/TCSDataContract")]
    [System.SerializableAttribute()]
    public partial class dc_TcsUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCSWcfServiceReference.InterfaceServiceTCS")]
    public interface InterfaceServiceTCS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServiceTCS/ValidUserAccess", ReplyAction="http://tempuri.org/InterfaceServiceTCS/ValidUserAccessResponse")]
        TCSWebSite.TCSWcfServiceReference.dc_User ValidUserAccess(string _userId, string _userPassword, string _applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServiceTCS/GetMenu", ReplyAction="http://tempuri.org/InterfaceServiceTCS/GetMenuResponse")]
        TCSWebSite.TCSWcfServiceReference.dc_Profile GetMenu(string _userId, string _applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServiceTCS/UsrUpdatePassword", ReplyAction="http://tempuri.org/InterfaceServiceTCS/UsrUpdatePasswordResponse")]
        TCSWebSite.TCSWcfServiceReference.dc_User UsrUpdatePassword(string _userId, string _userPassword, string _newPassword, string _applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServiceTCS/GetTcsUsers", ReplyAction="http://tempuri.org/InterfaceServiceTCS/GetTcsUsersResponse")]
        TCSWebSite.TCSWcfServiceReference.dc_TcsUser[] GetTcsUsers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceServiceTCSChannel : TCSWebSite.TCSWcfServiceReference.InterfaceServiceTCS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceServiceTCSClient : System.ServiceModel.ClientBase<TCSWebSite.TCSWcfServiceReference.InterfaceServiceTCS>, TCSWebSite.TCSWcfServiceReference.InterfaceServiceTCS {
        
        public InterfaceServiceTCSClient() {
        }
        
        public InterfaceServiceTCSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceServiceTCSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServiceTCSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServiceTCSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TCSWebSite.TCSWcfServiceReference.dc_User ValidUserAccess(string _userId, string _userPassword, string _applicationId) {
            return base.Channel.ValidUserAccess(_userId, _userPassword, _applicationId);
        }
        
        public TCSWebSite.TCSWcfServiceReference.dc_Profile GetMenu(string _userId, string _applicationId) {
            return base.Channel.GetMenu(_userId, _applicationId);
        }
        
        public TCSWebSite.TCSWcfServiceReference.dc_User UsrUpdatePassword(string _userId, string _userPassword, string _newPassword, string _applicationId) {
            return base.Channel.UsrUpdatePassword(_userId, _userPassword, _newPassword, _applicationId);
        }
        
        public TCSWebSite.TCSWcfServiceReference.dc_TcsUser[] GetTcsUsers() {
            return base.Channel.GetTcsUsers();
        }
    }
}
